spring:
  application:
    name: auth-service

server:
  port: 8001

feign:
  client:
    name:
      driver: driver-service
      passenger: passenger-service
    path:
      driver: api/v1/drivers
      passenger: api/v1/passengers

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

keycloak:
  user-management:
    client-id: ${CLIENT_ID:admin-cli}
    client-secret: ${CLIENT_SECRET:gGLx0I3KNeNAQFEf7EGoQB7SEQ1m5Hqw}
    username: ${KEYCLOAK_ADMIN_CLIENT_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_CLIENT_PASSWORD:admin}
    server-url: ${KEYCLOAK_ADMIN_CLIENT_URL:http://localhost:7000}

  auth:
    client-id: ${CLIENT_ID_FOR_AUTH_KC:cab-aggregator-app}
  realm: ${KC_REALM:cab-aggregator-app}