spring:
  application:
    name: gateway-service

  config:
    import: 'configserver:'
    activate:
      on-profile: default

  cloud:
    discovery:
      enabled: true

    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true