volumes:
  pg_passenger:
  pg_driver:
  pg_rating:
  pg_ride:
  kafka_data:
  zookeeper_data:

services:

  discovery-service:
    image: discovery-service
    build:
      context: ../discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - cab-aggregator-app

  config-server:
    image: config-server
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - cab-aggregator-app

  driver-service:
    image: driver-service:latest
    build:
      context: ../driver-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:postgresql://driver_db:5432/driver_db
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - KAFKA=kafka:29092
    networks:
      - cab-aggregator-app

  passenger-service:
    image: passenger-service:latest
    build:
      context: ../passenger-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://passenger_db:5432/passenger_db
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - KAFKA=kafka:29092
    networks:
      - cab-aggregator-app

  rating-service:
    image: rating-service:latest
    build:
      context: ../rating-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DB_URL=jdbc:postgresql://rating_db:5432/rating_db
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - KAFKA=kafka:29092
    networks:
      - cab-aggregator-app

  ride-service:
    image: ride-service:latest
    build:
      context: ../ride-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_URL=jdbc:postgresql://ride_db:5432/ride_db
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - cab-aggregator-app

  gateway-service:
    image: gateway-service:latest
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - cab-aggregator-app

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/wurstmeister/zookeeper
    networks:
      - cab-aggregator-app

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/wurstmeister/kafka
    networks:
      - cab-aggregator-app

  passenger_db:
    image: postgres:15.1-alpine
    container_name: passenger
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=passenger_db
    volumes:
      - pg_passenger:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - cab-aggregator-app

  driver_db:
    image: postgres:15.1-alpine
    container_name: driver
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=driver_db
    volumes:
      - pg_driver:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cab-aggregator-app

  ride_db:
    image: postgres:15.1-alpine
    container_name: ride
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=ride_db
    volumes:
      - pg_ride:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - cab-aggregator-app

  rating_db:
    image: postgres:15.1-alpine
    container_name: rating
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rating_db
    volumes:
      - pg_rating:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - cab-aggregator-app

networks:
  cab-aggregator-app: