global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cab-aggregator-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8000'
          - 'discovery-service:8761'
          - 'gateway-service:8888'
          - 'passenger-service:8081'
          - 'driver-service:8082'
          - 'ride-service:8083'
          - 'rating-service:8084'
        labels:
          group: 'cab-aggregator-app'