global:
  scrape_interval: 5s

scrape_configs:
  - job_name: eureka-discovery
    eureka_sd_configs:
      - server: http://discovery-service:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_metadata_metrics_path ]
        target_label: __metrics_path__
      - source_labels: [ __address__ ]
        target_label: instance
